### ISSUE TITLE
Content: Update Photos

### ISSUE THREAD

**Issue by wpaddiso999** [wpaddiso999/Corazon-de-oro#10]
**User Story**
As a user that wants to have some delicious dishes, I want to know exactly what the dish looks like so that I can decide whether I want to have that dish or not.

**Persona**
A user that wants to have some delicious dishes

**Feature**
The app should show what each dish looks like

**Business Value**
The user can decide whether they want to have that dish or not based on the pictures

**Tasks**

- [ ] collect the list of the items that need pictures
- [ ] collect the pictures for the items
- [ ] put the pictures in the appropriate places
- [ ] check whether the pictures show correctly on the app

**Acceptance Criteria**

1. The pictures should show correctly (ratio/size, not distorted, in correct color, correctly cropped) on the simulator
2. The pictures should show correctly (ratio/size, not distorted, in correct color, correctly cropped) on the phone
